[project]
name = "nx-mono-books"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.20.1",
    "ozlogger",
    "pytest>=9.0.3",
    "ruff>=0.15.11",
]

[tool.uv.workspace]
members = ["libs/*", "apps/*"]

[tool.uv.sources]
ozlogger = { workspace = true }
